(source marmalade)
(source melpa)

(depends-on "color-theme-solarized")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "exec-path-from-shell")
(depends-on "haskell-mode")
(depends-on "pallet")
(depends-on "shm")
